---
title: "stat436 project m2"
output: html_document
date: '2023-03-31'
runtime: shiny
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(shiny)
library(countrycode)
```
##Preprocessing our Data
```{r}
df <- read_csv("worldleaders.csv") %>%
  #eliminating unused columns
  select(4:6, 8, 10:12, 15, 29:39, 43, 47, 51:63, 65) %>%
  
  #eliminating rows which haven't yet been coded
  drop_na(Coder_1) %>%
  
  #extracting years from start and end dates, then using country codes to create columns containing country names and regions
  mutate(startyear = as.integer(substr(startdate, 1, 4)), endyear = as.integer(substr(enddate, 1, 4)), country = countrycode(.[[1]], origin = 'cowc', destination = 'country.name'), region = countrycode(country, origin = 'country.name', destination = 'region23')) %>%
  
  #combining columns to create one which lists all countries lived in by that leader
  mutate(countries_lived_in = paste(foreign_country_1, foreign_country_2, foreign_country_3, foreign_country_n, sep = ", ")) %>%
  mutate(countries_lived_in = gsub("NA, ","", countries_lived_in), countries_lived_in = gsub("NA","", countries_lived_in)) %>%
  
  #combining columns to create one which lists all countries traveled to by that leader
  mutate(countries_traveled_to = paste(travel_country_1, travel_country_2, travel_country_3, sep = ", ")) %>%
  mutate(countries_traveled_to = gsub("NA, ","", countries_traveled_to), countries_traveled_to = gsub("NA","", countries_traveled_to)) %>%
  
  #getting rid of columns that are now irrelevant
  select(-c(foreign_country_1, foreign_country_2, foreign_country_3, foreign_country_n,travel_country_1, travel_country_2, travel_country_3))

```

##Visualization 1:

```{r}
#additional mutations for map visualizations
data2 <- df %>%
  mutate(male = ifelse(gender=='M', 1, 0)) %>%
  mutate(regular = ifelse(entry=="Regular", 1, 0))

#country by country grouping
cbcdata <- data2 %>%
  group_by(country) %>%
  summarise_at(.vars=vars(Living_Abroad_Civilian, Military_Service_Abroad, 
                          Diplomatic, First_Gen_Immigrant, Study_Abroad_Civilian, 
                          Foreign_Language, male, regular),
               .funs = c(proportion="mean"), na.rm=TRUE)

#renaming to map specifications
cbcdata$country[cbcdata$country == "United States"] <- "USA"
cbcdata$country[cbcdata$country == "United Kingdom"] <- "UK"
cbcdata$country[cbcdata$country == "Bosnia & Herzegovina"] <- "Bosnia and Herzegovina"
cbcdata$country[cbcdata$country == "Congo - Brazzaville"] <- "Republic of Congo"
cbcdata$country[cbcdata$country == "Congo - Kinshasa"] <- "Democratic Republic of the Congo"
cbcdata$country[cbcdata$country == "Czechia"] <- "Czech Republic"
cbcdata$country[cbcdata$country == "Côte d’Ivoire"] <- "Ivory Coast"
cbcdata$country[cbcdata$country == "Myanmar (Burma)"] <- "Myanmar"

world_map <- map_data("world")

# joineddata <- cbcdata %>%
#  right_join(world_map, by=c("country"="region"), multiple="all")

# plot framework for outputs, decided to not facet nor repeat code as inteneded implementation was a shiny app

cbcdata %>%
  right_join(world_map, by=c("country" = "region")) %>%
  ggplot(aes(x=long, y=lat, group=group,
             fill=regular_proportion)) +
  geom_polygon(color="black") +
  theme_void() +
  scale_fill_viridis_c(direction=-1,option="C")

# unsuccessful attempt at shiny app, will be fixed on next iteration

# makemap <- function(df) {
#   ggplot(df, aes(x=long, y=lat, group=group,
#                fill=columnselected)) +
#     geom_polygon(color="black") +
#     theme_void() +
#     scale_fill_viridis_c(direction=-1,option="C")
# }
# 
# ui <- fluidPage(
#   titlePanel("Traits of Leaders by Country (since 1840)"),
#   sidebarPanel(
#     selectInput("select", "Select leader factor", names(cbcdata)[-1], multiple=FALSE)
#   ),
#   mainPanel(
#     plotOutput("makemap")
#   )
#   
# )
# 
# server <- function(input, output) {
#   columnselected <- reactive(names(df) %in% input$select)
#   output$makemap <- renderPlot(makemap(joineddata))
# }
# 
# app1 <- shinyApp(ui, server)
# runApp(app1)
```

##Visualization 2:

```{r}
#defining an external function to use country/region name and year inputs to filter the data
find_samples <- function(df, place, years) {
  filtered <- df %>%
    filter(grepl(place, country, ignore.case = TRUE) | grepl(place, region, ignore.case = TRUE)) %>%
    filter(startyear >= years[1] & endyear <= years[2])
  return(filtered)
}

years_abroad_pieplot <- function(df) {
  grouped <- df %>%
    filter(.[[18]] == 1) %>%
    mutate(mult_yrs = case_when(.[[19]] == 1 ~ "Less than one year", .[[20]] == 1 ~ "Between 1 and 5 years", .[[21]] == 1 ~ "Between 5 and 10 years", .[[22]] == 1 ~ "More than 10 years")) %>%
    group_by(mult_yrs) %>%
    summarize(count = n()) %>%
    drop_na()
  ggplot(grouped, aes(x="", y=count, fill=mult_yrs)) +
    geom_bar(stat="identity", width=1) +
    coord_polar("y", start=0) +
    guides(fill=guide_legend(title="Cumulative Time Spent Abroad"))
}

#creating a function which eliminates any columns that the output table shouldn't display
refine_table <- function(df) {
  refined <- df %>%
    select(leader, country, region, startyear, endyear, gender, Notes, countries_lived_in)
}

#defining the user interface with a title, side subtitle describing the purpose of my app, a text input box for the name of countries/regions, and a year range input
ui <- fluidPage(
   titlePanel("World Leaders"),
   sidebarLayout(
     sidebarPanel(),
     mainPanel(
       h4("Learn about the life experiences of the heads of state in the region/country and time period of your choosing!", align = "center")
       )
     ),
   sliderInput("yrs", "Please select the years you wish to include", c(1925, 2021), min=1925, max=2021, sep=""),
   textInput("place", "Please enter the name of a country or region", value = "", width = NULL, placeholder = NULL),
   plotOutput("piechart", width = 800, height = 400),
   dataTableOutput("list")
   
 )
 
#defining the server of my app, which calls my externally defined functions "find_samples" and "refine_table" to get a list output
 server <- function(input, output) {
   samples <- reactive({
     find_samples(df, input$place, input$yrs)
   })
   output$piechart <- renderPlot(years_abroad_pieplot(samples()))
   output$list <- renderDataTable(refine_table(samples()))
 }
 
#running my app
shinyApp(ui, server)
```